Repository tukcom2023CD/AOK, pull requests merged in 2023-04, with the labels that each got.

#58 [Design/#52] 업로드 페이지 디자인 수정 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/ActionCard.tsx
  frontend/src/Components/DragDrop/DragDrop.scss
  frontend/src/Components/DragDrop/DragDrop.tsx
  frontend/src/Components/FeedBack.tsx
  frontend/src/Components/FileList.tsx
  frontend/src/Components/List.tsx
  frontend/src/Components/Profile.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Components/Seekbar.tsx
  frontend/src/Components/Seekbars.tsx
  frontend/src/Components/SelectBar.tsx
  frontend/src/Components/Slider.tsx
  frontend/src/Components/StickList.tsx
  frontend/src/Pages/LogHistory.tsx
  frontend/src/Pages/LogHistory2.tsx
  frontend/src/Pages/Upload.tsx
  frontend/src/index.css
  frontend/yarn.lock
Labels: 퍼블리싱

#65 [Design/#61]
  frontend/src/App.tsx
  frontend/src/Components/ColorTab.tsx
  frontend/src/Components/List.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Components/SelectBar.tsx
  frontend/src/Pages/LogHistory.tsx
  frontend/src/Pages/LogHistory2.tsx
  frontend/src/Pages/Main.tsx
  frontend/src/Pages/Project.tsx
Labels: 퍼블리싱

#72 [Design/#70] 상단바 교체
  frontend/src/Pages/Main.tsx
Labels: 퍼블리싱

#76 [Feat/#73]main page 기능 구현
  frontend/.yarn/cache/@emotion-cache-npm-11.10.5-e5bc83f178-1dd2d9af2d.zip
  frontend/.yarn/cache/@mui-private-theming-npm-5.11.13-3d71420ae2-9e5e02c648.zip
  frontend/.yarn/cache/@mui-styled-engine-npm-5.11.11-0e7d47c170-63b71aafe7.zip
  frontend/.yarn/cache/@mui-system-npm-5.11.13-9eca9ab5d4-e6f1852ecf.zip
  frontend/.yarn/cache/@mui-types-npm-7.2.3-36b2c98922-b8511cb78f.zip
  frontend/.yarn/cache/@mui-utils-npm-5.11.13-b71980ec12-0f403f2635.zip
  frontend/.yarn/cache/@popperjs-core-npm-2.11.6-5bcdc104bd-47fb328cec.zip
  frontend/.yarn/cache/@remix-run-router-npm-1.2.1-b89e8a23a3-71c947f83e.zip
  frontend/.yarn/cache/@remix-run-router-npm-1.5.0-34ae8a468b-9c510c174a.zip
  frontend/.yarn/cache/@types-react-beautiful-dnd-npm-13.1.4-5fc92fb3be-76220f1031.zip
  frontend/.yarn/cache/@types-react-redux-npm-7.1.25-03bcc651fd-a61ec25cbf.zip
  frontend/.yarn/cache/css-box-model-npm-1.2.1-d4e0001730-4d113f26fe.zip
  frontend/.yarn/cache/csstype-npm-3.1.1-3857baf48b-1f7b4f5fdd.zip
  frontend/.yarn/cache/raf-schd-npm-4.0.3-18f72af738-45514041c5.zip
  frontend/.yarn/cache/react-beautiful-dnd-npm-13.1.1-ddc8adf565-5f90f7c0ab.zip
  frontend/.yarn/cache/react-redux-npm-7.2.9-612aa35519-369a2bdcf8.zip
  frontend/.yarn/cache/react-router-dom-npm-6.10.0-c8bb29573e-d048d8cc66.zip
  frontend/.yarn/cache/react-router-dom-npm-6.6.2-282252e9b6-e0ee89a2b3.zip
  frontend/.yarn/cache/react-router-npm-6.10.0-a4f053634d-c9fce46147.zip
  frontend/.yarn/cache/react-router-npm-6.6.2-c53a062a14-5960d774bb.zip
  frontend/.yarn/cache/tiny-invariant-npm-1.3.1-a8ca214e49-872dbd1ff2.zip
  frontend/.yarn/cache/use-memo-one-npm-1.1.3-b9dc77468a-8f08eba26d.zip
  frontend/.yarn/install-state.gz
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/Button.tsx
  frontend/src/Components/ColorTab.tsx
  frontend/src/Components/DragDrop/DragDrop.scss
  frontend/src/Components/DragDrop/DragDrop.tsx
  frontend/src/Components/Dropmenu.tsx
  frontend/src/Components/MainModal.tsx
  frontend/src/Components/Modalcom.tsx
  frontend/src/Pages/Main.tsx
  frontend/src/Pages/Project.tsx
  frontend/src/Pages/Upload.tsx
  frontend/src/global.d.ts
  frontend/yarn.lock
Labels: 기능구현

#77 [Feat/#69] 로그 히스토리 페이지 슬라이더 기능 보안
  frontend/.yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  frontend/.yarn/cache/date-fns-npm-2.29.3-fef7e3c72c-e01cf5b62a.zip
  frontend/.yarn/cache/react-datepicker-npm-4.11.0-5af1e7d387-6936eaa2f9.zip
  frontend/.yarn/cache/react-fast-compare-npm-3.2.1-c0b870cc30-209b4dc3a9.zip
  frontend/.yarn/cache/react-onclickoutside-npm-6.13.0-c9116fb62e-a7cfe62e91.zip
  frontend/.yarn/cache/react-popper-npm-2.3.0-1045578379-837111c987.zip
  frontend/.yarn/cache/warning-npm-4.0.3-291e921d6d-4f2cb6a957.zip
  frontend/.yarn/install-state.gz
  frontend/package.json
  frontend/src/Components/DateSlider.tsx
  frontend/src/Components/Slider.tsx
  frontend/src/Pages/LogHistory.tsx
  frontend/yarn.lock
Labels: 기능구현

#79 [design/#75] 사이드바 개선 완료
  frontend/src/Components/BranchModal.tsx
  frontend/src/Components/CreateBtn.tsx
  frontend/src/Components/List.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Pages/LogHistory.tsx
  frontend/src/Pages/Main.tsx
  frontend/src/Pages/Project.tsx
  frontend/src/Pages/Upload.tsx
Labels: 퍼블리싱

#80 [Feat/#55] 유저 API 설계
  backend/build.gradle
  backend/src/main/java/crepe/backend/domain/log/controller/LogController.java
  backend/src/main/java/crepe/backend/domain/log/domain/repository/LogRepository.java
  backend/src/main/java/crepe/backend/domain/log/service/LogService.java
  backend/src/main/java/crepe/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/crepe/backend/domain/project/domain/entity/Project.java
  backend/src/main/java/crepe/backend/domain/project/dto/ProjectInfo.java
  backend/src/main/java/crepe/backend/domain/project/dto/ProjectInfoList.java
  backend/src/main/java/crepe/backend/domain/project/service/ProjectService.java
  backend/src/main/java/crepe/backend/domain/user/controller/UserController.java
  backend/src/main/java/crepe/backend/domain/user/domain/entity/User.java
  backend/src/main/java/crepe/backend/domain/user/domain/repository/UserRepository.java
  backend/src/main/java/crepe/backend/domain/user/dto/UserCreate.java
  backend/src/main/java/crepe/backend/domain/user/dto/UserCreateInfo.java
  backend/src/main/java/crepe/backend/domain/user/dto/UserInfo.java
  backend/src/main/java/crepe/backend/domain/user/exception/NotFoundUserEntityException.java
  backend/src/main/java/crepe/backend/domain/user/service/UserService.java
  backend/src/main/java/crepe/backend/domain/userproject/domain/entity/UserProject.java
  backend/src/main/java/crepe/backend/domain/userproject/domain/repository/UserProjectRepository.java
  backend/src/main/java/crepe/backend/global/exception/BusinessException.java
  backend/src/main/java/crepe/backend/global/response/ErrorCode.java
  backend/src/main/java/crepe/backend/global/response/ResultCode.java
  backend/src/main/java/crepe/backend/global/response/ResultResponse.java
Labels: 기능구현

#74 [feat/#63] 업로드 페이지 기능 구현 완료
  frontend/package.json
  frontend/src/Components/DragDrop/DragDrop.scss
  frontend/src/Components/DragDrop/DragDrop.tsx
  frontend/src/Components/Lottie/uploding.json
  frontend/src/Components/LottieUpload.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Pages/Upload.tsx
  frontend/yarn.lock
Labels: 기능구현

#85 [Fix/#84] merge 오류 수정
  backend/src/main/java/crepe/backend/domain/branch/controller/BranchController.java
  backend/src/main/java/crepe/backend/domain/project/domain/entity/Project.java
  backend/src/main/java/crepe/backend/domain/user/domain/entity/User.java
  backend/src/main/java/crepe/backend/domain/user/dto/UserCreate.java
  backend/src/main/java/crepe/backend/domain/user/service/UserService.java
  backend/src/main/java/crepe/backend/domain/userProject/domain/entity/UserProject.java
  backend/src/main/java/crepe/backend/domain/userProject/domain/repository/UserProjectRepository.java
  backend/src/main/java/crepe/backend/domain/userproject/domain/entity/UserProject.java
  backend/src/main/java/crepe/backend/domain/userproject/domain/repository/UserProjectRepository.java
Labels: 오류수정

#87 [Fix/#86] UserService 오류 해결
  backend/src/main/java/crepe/backend/domain/branch/controller/BranchController.java
  backend/src/main/java/crepe/backend/domain/user/service/UserService.java
Labels: 오류수정

#91 [Feat/#78] 프로젝트브랜치 페이지 제목 수정 버튼 기능 구현
  frontend/.yarn/cache/@fortawesome-fontawesome-common-types-npm-6.4.0-8174465a2e-a9b79136ca.zip
  frontend/.yarn/cache/@fortawesome-fontawesome-svg-core-npm-6.4.0-bc7699426e-5d4e6c15f8.zip
  frontend/.yarn/cache/@reduxjs-toolkit-npm-1.9.5-4da955008b-54672c5593.zip
  frontend/.yarn/cache/@types-axios-npm-0.14.0-42f41917ea-12a230b940.zip
  frontend/.yarn/cache/@types-bootstrap-npm-5.2.6-2e04aa5d73-e8e161fcaa.zip
  frontend/.yarn/cache/@types-react-bootstrap-npm-0.32.32-63b8fc7657-93e98ab7ad.zip
  frontend/.yarn/cache/@types-use-sync-external-store-npm-0.0.3-875a91a914-161ddb8eec.zip
  frontend/.yarn/cache/axios-npm-1.3.5-f8ffbd6db8-4d6bcf933b.zip
  frontend/.yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  frontend/.yarn/cache/immer-npm-9.0.21-03c48c58ea-70e3c27416.zip
  frontend/.yarn/cache/jwt-decode-npm-3.1.2-bf3ab26591-20a4b072d4.zip
  frontend/.yarn/cache/proxy-from-env-npm-1.1.0-c13d07f26b-ed7fcc2ba0.zip
  frontend/.yarn/cache/react-redux-npm-8.0.5-9ff31aed95-a108f4f7ea.zip
  frontend/.yarn/cache/redux-npm-4.2.1-e7e2cf2e37-f63b9060c3.zip
  frontend/.yarn/cache/redux-thunk-npm-2.4.2-3acdaaf7b0-c7f757f6c3.zip
  frontend/.yarn/cache/reselect-npm-4.1.8-cad5f0a3f3-a4ac87ceda.zip
  frontend/.yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  frontend/.yarn/install-state.gz
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/Title/EditTitle.tsx
  frontend/src/Components/Title/Title.tsx
  frontend/src/Components/Title/TitleList.tsx
  frontend/src/Pages/Project.tsx
  frontend/src/Pages/Side.tsx
  frontend/src/contexts/TitleContext.tsx
  frontend/yarn.lock
Labels: 기능구현

#90 [feat/#81] 모달 및 기본 라우팅 세팅 완료
  frontend/src/Components/ApplyModal.tsx
  frontend/src/Components/ColorTab.tsx
  frontend/src/Components/DDProjectModal.tsx
  frontend/src/Components/Dropmenu.tsx
  frontend/src/Components/List.tsx
  frontend/src/Components/MergeModal.tsx
  frontend/src/Components/ProjectModal.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Components/UpsideGray.tsx
  frontend/src/Pages/LogHistory.tsx
  frontend/src/Pages/Main.tsx
  frontend/src/Pages/Project.tsx
  frontend/src/Pages/Upload.tsx
Labels: 기능구현

#100 [feat#96] REST API user 부분 연결
  frontend/package.json
  frontend/src/Components/DDProjectModal.tsx
  frontend/src/Components/Profile.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Components/Redux/Store.tsx
  frontend/src/Components/Redux/UserSlice.tsx
  frontend/src/Pages/Main.tsx
  frontend/src/index.tsx
  frontend/yarn.lock
Labels: 기능구현

#99 [Feat/#97] Feedback api 구현
  backend/src/main/java/crepe/backend/domain/branch/controller/BranchController.java
  backend/src/main/java/crepe/backend/domain/branch/domain/entity/Branch.java
  backend/src/main/java/crepe/backend/domain/branch/domain/repository/BranchRepository.java
  backend/src/main/java/crepe/backend/domain/branch/service/BranchService.java
  backend/src/main/java/crepe/backend/domain/feedback/controller/FeedbackController.java
  backend/src/main/java/crepe/backend/domain/feedback/domain/entity/Feedback.java
  backend/src/main/java/crepe/backend/domain/feedback/domain/repository/FeedbackRepository.java
  backend/src/main/java/crepe/backend/domain/feedback/dto/FeedbackCreate.java
  backend/src/main/java/crepe/backend/domain/feedback/dto/FeedbackCreateInfo.java
  backend/src/main/java/crepe/backend/domain/feedback/dto/FeedbackInfo.java
  backend/src/main/java/crepe/backend/domain/feedback/exception/NotFoundFeedbackEntityException.java
  backend/src/main/java/crepe/backend/domain/feedback/service/FeedbackService.java
  backend/src/main/java/crepe/backend/domain/log/domain/repository/LogRepository.java
  backend/src/main/java/crepe/backend/domain/log/exception/NotFoundLogEntityException.java
  backend/src/main/java/crepe/backend/domain/user/domain/entity/User.java
  backend/src/main/java/crepe/backend/domain/user/service/UserService.java
  backend/src/main/java/crepe/backend/domain/userProject/domain/repository/UserProjectRepository.java
  backend/src/main/java/crepe/backend/global/response/ErrorCode.java
  backend/src/main/java/crepe/backend/global/response/ResultCode.java
Labels: 기능구현

#103 [Fix/#102] LogInfo를 BranchLogInfo로 수정
  backend/src/main/resources/application.yml
Labels: 오류수정

#111 [feat/#101] Rest API 프로젝트, 브랜치 파트 연결 완료
  frontend/src/App.tsx
  frontend/src/Components/ColorTab.tsx
  frontend/src/Components/DDProjectModal.tsx
  frontend/src/Components/ImgList.tsx
  frontend/src/Components/List.tsx
  frontend/src/Components/Logincom2.tsx
  frontend/src/Components/MergeModal.tsx
  frontend/src/Components/MergeModal_Button.tsx
  frontend/src/Components/Profile.tsx
  frontend/src/Components/ProjectModal.tsx
  frontend/src/Components/ProjectSelect.tsx
  frontend/src/Components/Redux/BranchSlice.tsx
  frontend/src/Components/Redux/ProjectSlice.tsx
  frontend/src/Components/Redux/Store.tsx
  frontend/src/Components/SelectBar.tsx
  frontend/src/index.tsx
Labels: 기능구현

#113 [fix/#112] merge 페이지와 upload 페이지 간 오류 수정
  frontend/src/Components/DragDrop/DragDrop.module2.css
  frontend/src/Components/DragDrop/DragDrop.scss
  frontend/src/Components/DragDrop/DragDrop.tsx
  frontend/src/Components/Dropmenu.tsx
  frontend/src/Components/Merge/DragDrop2.tsx
  frontend/src/Components/Merge/Merge.module.css
  frontend/src/Components/Merge/Merge.scss
  frontend/src/Components/Merge/MergeComp.tsx
  frontend/src/Components/MergeIconModal.tsx
  frontend/src/Components/UpsideGray.tsx
  frontend/src/Pages/Merge.tsx
Labels: 오류수정

#115 [fix] main 페이지 상단 바 수정
  frontend/src/Components/nonSelectBar.tsx
  frontend/src/Pages/Main.tsx
Labels: 오류수정

#118 [refactor] delete LayerService
  backend/src/main/java/crepe/backend/domain/log/controller/LogController.java
  backend/src/main/java/crepe/backend/domain/log/service/LayerService.java
Labels: 리팩토링

#119 [Feat] B007 머지 리소스 리스트 반환 기능 구현
  backend/src/main/java/crepe/backend/domain/branch/controller/BranchController.java
  backend/src/main/java/crepe/backend/domain/branch/dto/MergeResourceInfo.java
  backend/src/main/java/crepe/backend/domain/branch/dto/MergeResourceInfoList.java
  backend/src/main/java/crepe/backend/domain/branch/service/BranchService.java
  backend/src/main/java/crepe/backend/domain/log/domain/repository/LayerRepository.java
  backend/src/main/java/crepe/backend/global/response/ResultCode.java
Labels: 기능구현
